apiVersion: v1
kind: Deployment
metadata:
  name: web
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      service: web-service
  template:
    metadata:
      labels:
        app: web
        service: web-service
    spec:
      containers:
      - name: web
        image: ndricimdanaj/javacicd
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080