apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
  labels:
    app: web
    service: web-service
spec:
  selector:
    app: web
    service: web-serice
  ports:
  - protocol: TCP
    targetPort: 9080
    name: port-8000-tcp
    port: 8080